// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/arango/connection.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/arango/connection.go -destination=internal/mocks/arango_connection.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	arangodb "github.com/arangodb/go-driver/v2/arangodb"
	gomock "go.uber.org/mock/gomock"
)

// MockArangoDB is a mock of ArangoDB interface.
type MockArangoDB struct {
	ctrl     *gomock.Controller
	recorder *MockArangoDBMockRecorder
	isgomock struct{}
}

// MockArangoDBMockRecorder is the mock recorder for MockArangoDB.
type MockArangoDBMockRecorder struct {
	mock *MockArangoDB
}

// NewMockArangoDB creates a new mock instance.
func NewMockArangoDB(ctrl *gomock.Controller) *MockArangoDB {
	mock := &MockArangoDB{ctrl: ctrl}
	mock.recorder = &MockArangoDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArangoDB) EXPECT() *MockArangoDBMockRecorder {
	return m.recorder
}

// Database mocks base method.
func (m *MockArangoDB) Database(ctx context.Context) arangodb.Database {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Database", ctx)
	ret0, _ := ret[0].(arangodb.Database)
	return ret0
}

// Database indicates an expected call of Database.
func (mr *MockArangoDBMockRecorder) Database(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Database", reflect.TypeOf((*MockArangoDB)(nil).Database), ctx)
}

// GetCollection mocks base method.
func (m *MockArangoDB) GetCollection(ctx context.Context, name string) (arangodb.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", ctx, name)
	ret0, _ := ret[0].(arangodb.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockArangoDBMockRecorder) GetCollection(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockArangoDB)(nil).GetCollection), ctx, name)
}
