server:
  port: "8080"
  host: "0.0.0.0"
  mode: "development"
  read_timeout: 10  # seconds
  write_timeout: 10 # seconds

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "123456"
  dbname: "myapp"
  sslmode: "disable"
  max_conns: 20
  min_conns: 1

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  max_retries: 3
  pool_size: 100
  min_idle_conns: 10
  dial_time_out: 5
  read_time_out: 3
  write_time_out: 3
  idle_time_out: 5

jwt:
  secret: "your-super-secret-key-should-be-at-least-32-chars"
  expire_hour: 24
  refresh_expire_day: 7

    