server:
  port: "8080"
  host: "0.0.0.0"
  mode: "development"

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "myapp"
  sslmode: "disable"
  max_conns: 10
  min_conns: 1

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expire_hour: 24

log_level: "info"
