server:
  port: "8080"
  host: "0.0.0.0"
  mode: "production"
  read_timeout: 10  # seconds
  write_timeout: 10 # seconds

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "1234"
  dbname: "vinama"
  sslmode: "disable"
  max_conns: 20
  min_conns: 1

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  max_retries: 3
  pool_size: 100
  min_idle_conns: 10

jwt:
  secret: "your-super-secret-key-should-be-at-least-32-chars"
  expire_hour: 24
  refresh_expire_day: 7

logger:
  level: "info"
  encoder_config:
    message_key: "msg"
    level_key: "level"
    name_key: "logger"
  rotation_config:
    filename: "var/lib/test.txt"
    max_size: 500
    max_backups: 2
    max_age: 1
    